### ISSUE TITLE
Babel/Webpack related error at npm start

### ISSUE THREAD

**Issue by aaj** [pydanny/cookiecutter-django#711] opened 2016-08-04 03:08 UTC
Running the setup process works fine up until the `npm start` command where I get the following error:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'babel',
1 verbose cli   '--',
1 verbose cli   './node_modules/.bin/webpack-dev-server',
1 verbose cli   '--progress',
1 verbose cli   '--hot\'' ]
2 info using npm@3.10.3
3 info using node@v6.3.1
4 verbose run-script [ 'prebabel', 'babel', 'postbabel' ]
5 info lifecycle test@0.1.0~prebabel: test@0.1.0
6 silly lifecycle test@0.1.0~prebabel: no script for prebabel, continuing
7 info lifecycle test@0.1.0~babel: test@0.1.0
8 verbose lifecycle test@0.1.0~babel: unsafe-perm in lifecycle true
9 verbose lifecycle test@0.1.0~babel: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;E:\Users\Armando\Documents\Dev\Django\Projects\test\test\node_modules\.bin;C:\Program Files\nodejs;E:\Users\Armando\Documents\Dev\venvs\test\Scripts;C:\Python27\;C:\Python27\Scripts;C:\Program Files (x86)\Python35-32\Scripts\;C:\Program Files (x86)\Python35-32\;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\ThinkPad\Bluetooth Software\;C:\Program Files\ThinkPad\Bluetooth Software\syswow64;E:\Users\Armando\Documents\Dev\UnixTools;E:\Users\Armando\Documents\Dev\Tools\Ant\apache-ant-1.9.3\bin;C:\Program Files (x86)\Git\cmd;C:\Python27;C:\Python27\Scripts;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;E:\Users\Armando\Documents\Dev\android\adt-bundle-windows-x86_64-20140321\sdk\platform-tools\;E:\Users\Armando\Documents\Dev\android\adt-bundle-windows-x86_64-20140321\sdk\tools\;C:\Program Files (x86)\Windows Live\Shared;E:\Users\Armando\Documents\Dev\android\adt-bundle-windows-x86_64-20140321\sdk\build-tools\android-4.4.2\;C:\Program Files (x86)\PostgreSQL\9.2\bin\;C:\Program Files (x86)\Unity\Editor\Data\MonoBleedingEdge\lib\mono\4.0\;C:\Program Files (x86)\Unity\Editor\Data\Mono\bin\;C:\Program Files (x86)\Java\jdk1.7.0_79\bin\;C:\Python34\;C:\Python34\Scripts\;E:\Users\Armando\Documents\Dev\Tools\PhantomJS\bin\;C:\Users\Armando\AppData\Roaming\npm;C:\Program Files (x86)\Microsoft Visual Studio\Common\Tools\WinNT;C:\Program Files (x86)\Microsoft Visual Studio\Common\MSDev98\Bin;C:\Program Files (x86)\Microsoft Visual Studio\Common\Tools;C:\Program Files (x86)\Microsoft Visual Studio\VC98\bin;C:\Rust\bin;C:\Users\Armando\AppData\Local\Tesseract-OCR;C:\OSGeo4W\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft Network Monitor 3\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files\Redis\;C:\HashiCorp\Vagrant\bin;C:\Program Files\nodejs\;E:\Users\Armando\Documents\Dev\android\adt-;E:\Users\Armando\Documents\Dev\gettext-utils-0.17\bin
10 verbose lifecycle test@0.1.0~babel: CWD: E:\Users\Armando\Documents\Dev\Django\Projects\test\test
11 silly lifecycle test@0.1.0~babel: Args: [ '/d /s /c',
11 silly lifecycle   'babel-node --presets es2015 "./node_modules/.bin/webpack-dev-server" "--progress" "--hot\'"' ]
12 silly lifecycle test@0.1.0~babel: Returned: code: 1  signal: null
13 info lifecycle test@0.1.0~babel: Failed to exec babel script
14 verbose stack Error: test@0.1.0 babel: `babel-node --presets es2015 "./node_modules/.bin/webpack-dev-server" "--progress" "--hot'"`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid test@0.1.0
16 verbose cwd E:\Users\Armando\Documents\Dev\Django\Projects\test\test
17 error Windows_NT 10.0.10586
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "babel" "--" "./node_modules/.bin/webpack-dev-server" "--progress" "--hot'"
19 error node v6.3.1
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error test@0.1.0 babel: `babel-node --presets es2015 "./node_modules/.bin/webpack-dev-server" "--progress" "--hot'"`
22 error Exit status 1
23 error Failed at the test@0.1.0 babel script 'babel-node --presets es2015 "./node_modules/.bin/webpack-dev-server" "--progress" "--hot'"'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the test package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     babel-node --presets es2015 "./node_modules/.bin/webpack-dev-server" "--progress" "--hot'"
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs test
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls test
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

I'm on windows, python 2.7.

**Comment by paulalbrecht** [comment] 2016-08-05 19:48
Can confirm on Ubuntu 16 python 2.7

**Comment by pydanny** [comment] 2016-08-05 20:25
ping @goldhand

**Comment by kjg531** [comment] 2016-08-07 06:18
I just encountered this as well, same error. Seems for me @paulalbrecht workaround did not solve my issue.

**Comment by darwin4031** [comment] 2016-08-08 12:58
because :
[https://github.com/babel/babel/blob/master/CHANGELOG.md#loose-and-modules-options-for-babel-preset-es2015-3331-3627](url)

change .babelrc preset:
from : 
`"presets": ["es2015-webpack", "stage-0", "react"],`

to:
`"presets": [["es2015", {"modules": false}], "stage-0", "react"]`

and stop using es2015-webpack preset

**Comment by goldhand** [comment] 2016-08-14 23:19
Sorry for the delay! I've been away for a couple weeks.

@darwin4031 do you not get an error when you use `{"modules": false}`?

You're solution should work since `babel v6.13.0` was released and [`babel-preset-es2015-webpack` was depreciated](https://github.com/gajus/babel-preset-es2015-webpack/tree/43b22a51ef98b060232b0b3797facc9d30337b02#deprecated) but I'm getting an error when I add this fix:

`Using removed Babel 5 option: base.modules - Use the corresponding module transform plugin in the plugins option. Check out http://babeljs.io/docs/plugins/#modules`

I have a feeling it's because I'm using `babel-node` to run webpack instead of just node (because the webpack config uses es6 syntax that native node doesn't support).

[This commit](https://github.com/hzdg/cookiecutter-webpack/commit/d207c5ca4c0a6b38131b9a5ecde57cee0ac19e02) should resolve the issue but I think tree-shaking may be disabled now that babel is transpiling es6 into commonjs but I'm not sure. Like I mentioned, I've been unplugged for the last couple weeks when the `v6.13.0` update came out and it seems like a lots been going on with babel recently.

I think this issue can be closed for now but it might be a good idea to bring up a new issue in [cookiecutter-webpack](https://github.com/hzdg/cookiecutter-webpack/issues) and mention this issue if it can be confirmed the tree-shaking is now disabled.

**Comment by goldhand** [comment] 2016-08-14 23:47
Never mind about all that clutter, I forgot the extra brackets. :sob: this is [fixed now](https://github.com/hzdg/cookiecutter-webpack/commit/1c80a24088c7540ad11212641c3679925d6e7770)

**Closed** 2016-10-07 20:50 UTC
