### ISSUE TITLE
Docker dev enviroment not working: python: can't open file '/app/manage.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by cepinos** [pydanny/cookiecutter-django#356] opened 2015-10-01 16:05 UTC
I am trying to run the docker dev environment and this throw me this error: python: can't open file '/app/manage.py': [Errno 2] No such file or directory

I am using ubuntu 14.04 LTS as host machine.

I ran this command $docker-compose -f dev.yml up

**Comment by jayfk** [comment] 2015-10-01 16:16
This is probably a permission problem. Do you run ubuntu on bare metal with a native docker installation, or is this on a VM with a docker remote daemon or something similar?

Can you run 
    
    pwd
    docker run -v $(pwd):/test -it ubuntu ls -la test

in you project folder and post the output here?

**Comment by cepinos** [comment] 2015-10-01 16:31
Hi @jayfk Thanks for respond! 

I am not sure what bare metal means, sorry :$. but my machine have Ubuntu installed native. 

I am following this instructions http://cookiecutter-django.readthedocs.org/en/latest/developing-locally-docker.html, so I guess docker will run in a VM, but also, I have docker running in the host machine. 

I ran the commands you asked me to run,

$pwd                                                                                                                                                                                                       /home/expedienteweb/inqbation/django-508q

docker run -v $(pwd):/test -it ubuntu ls -la test                                                                                                                                                         
WARNING: Error loading config file:open /home/expedienteweb/.dockercfg: permission denied
Unable to find image 'ubuntu:latest' locally
latest: Pulling from library/ubuntu
d3a1f33e8a5a: Pull complete 
c22013c84729: Pull complete 
d74508fb6632: Pull complete 
91e54dfb1179: Pull complete 
library/ubuntu:latest: The image you are pulling has been verified. Important: image verification is a tech preview feature and should not be relied on to provide security.
Digest: sha256:73fbe2308f5f5cb6e343425831b8ab44f10bbd77070ecdfbe4081daa4dbe3ed1
Status: Downloaded newer image for ubuntu:latest
total 4
drwxr-xr-x  2 root root   40 Oct  1 15:17 .
drwxr-xr-x 33 root root 4096 Oct  1 16:21 ..

Thanks a lot for you support!

**Comment by cepinos** [comment] 2015-10-01 17:03
Hi @jayfk, I was able to run it without the VM, I think maybe it could be a permissions problem, as you said. My partners are experimenting the same problem, they have mac as a host machine.

**Comment by jayfk** [comment] 2015-10-02 07:05
On ubuntu you have native docker, so you don't need to create a vm with `docker-machine` to use it. Always use this, it's the best thing you can get :)

On a vm created with `docker-machine` the docker daemon runs inside a vm (boot2docker) with its own file system and you configure your terminal to use a remote docker daemon. The problem is that the remote docker daemon has no access to the files on your host machine and therefore can't find `manage.py` and raises `No such file or directory`. On OS X and Windows `~/` is auto-mounted into the vm to solve this problem. I don't know about ubuntu. It could be that virtual box has no file sharing feature for that, but I honestly don't know.

I'm not closing this as a remainder to rework the docker specific documentation, but this has nothing to do with `cookiecutter-django` per se.

**Comment by cepinos** [comment] 2015-10-02 13:04
Great! I think that clarify everything. At this moment I am running docker without VirtualBox, and it did the trick.  

Thanks for your help!

**Closed** 2015-10-24 17:46 UTC

**Comment by sakhmedbayev** [comment] 2016-04-04 11:41
Hi @cepinos ! Can you please tell community, how you managed to install cookiecutter-django with docker on ubuntu. I have been trying to make it work for several days. No luck so far :-(
