### ISSUE TITLE
App model doesn't appear in Django admin in production

### ISSUE THREAD

**Issue by tommeagher** [pydanny/cookiecutter-django#162] opened 2014-12-08 20:22 UTC
Danny, 
First of all, thank you for this. It exponentially speeded up my starting a new project. Everything was going along swimmingly until I moved to production. I put this up as a question on StackOverflow that is totally empty.

The short version is this: The model for my app works fine in my local runserver. When I deploy to Heroku, everything works perfectly except my app doesn't show up in the Django admin.

Here's the long version:

I've been building a Django app and testing locally for some time. On my machine, when I visit the admin page, my app appears. When I deploy to Heroku, it no longer does. The odd thing is that when setting user permissions in the admin, I can access the tables for my app in the postgres db, so it doesn't appear to be a db issue, just my custom admin is not being found or loaded.

My directory listing is roughly this

```
overall
    - myproject
        manage.py
        urls.py
        wsgi.py
        -templates
        -contrib
        -users
        -myapp
            admin.py
            forms.py
            models.py
            fixtures
```

My urls.py file
```
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = patterns('',
    url(r'^$',  # noqa
        TemplateView.as_view(template_name='pages/home.html'),
        name="home"),
    url(r'^about/$',
        TemplateView.as_view(template_name='pages/about.html'),
        name="about"),

# Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls), name="admin"),

# User management
    url(r'^users/', include("users.urls", namespace="users")),
    url(r'^accounts/', include('allauth.urls')),

# Uncomment the next line to enable avatars
    url(r'^avatar/', include('avatar.urls')),

# Your stuff: custom urls go here

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
```

In myapp/admin.py, I have this:

```
from django.contrib import admin
from myapp.models import State, Facility, Report
from forms import ReportForm

@admin.register(State)
class StateAdmin(admin.ModelAdmin):
    list_display=('state_name','state_abbrev')
    ordering=('state_name',)

@admin.register(Faculty)
class FacultyAdmin(admin.ModelAdmin):
    pass
```

In my django settings on heroku, i have this:

```
INSTALLED_APPS = ('django.contrib.auth', 'django.contrib.contenttypes', 'django.contrib.sessions',      
'django.contrib.sites', 'django.contrib.messages', 'django.contrib.staticfiles', 'suit', 
'django.contrib.admin', 'crispy_forms', 'allauth', 'allauth.account', 'allauth.socialaccount', 
'users', 'myapp', 'djangosecure', 'gunicorn', 'storages', 'collectfast')
```

But my admin only contains users, sites, accounts in it, and not myapp, like it does on my local testing environment.

(In a separate issue, when I try to use heroku's foreman to test the app locally, it can't seem to find the environment variables to run gunicorn, so that's tripping up my debugging too. )

Please, please help me figure this out. It's driving me crazy. Any advice would be greatly appreciated.

Thanks!

**Comment by theskumar** [comment] 2015-02-24 13:05
closing this as we don't have any conclusive answer for it. Thanks @tommeagher for reporting this. 

Anyone facing the same issue, please re-open it and we would be happy to help.

**Closed by theskumar** 2015-02-24 13:05 UTC

**Comment by dkpapo** [comment] 2015-03-11 20:41
i have also the problem, i dont know how resolve this pls any help me

**Comment by theskumar** [comment] 2015-03-11 20:57
Hey @dkpapo, if you can __show some code__ then I'm happy to help. 

PS: If you are able to isolate your problem and make it reproducible, that going to be super helpful.

cheers,

**Comment by dkpapo** [comment] 2015-03-11 22:37
thanx theskumar i  resolved the problem was use admin.autodiscover() in my urls  

from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    .........
)

**Comment by theskumar** [comment] 2015-03-12 07:34
:+1:

**Comment by ddaitest** [comment] 2017-04-14 06:36
try to restart uwsgi. it works for me.

**Comment by Cvmsingh** [comment] 2019-10-14 19:44
> Hey @dkpapo, if you can **show some code** then I'm happy to help.
> 
> PS: If you are able to isolate your problem and make it reproducible, that going to be super helpful.
> 
> cheers,

from django.contrib import admin

# Register your models here.
from .models import Contact

admin.site.register(Contact)

**Comment by mchesler613** [comment] 2021-04-22 18:31
I had this problem today in production. Just had to restart the server.  :)

**Comment by AffanAhmedUsmani** [comment] 2023-08-28 21:57
In production make sure you make the debug mode in settings.py to FALSE
and ALLOWED_HOST =["*"]
First write this command:
`sudo systemctl reload nginx.service`
if this doesn' work then write this 
`sudo reboot`
after this run 
`systemctl status nginx.service`
this shoudl do the job
