### ISSUE TITLE
Missing "libpng-dev" requirement breaks thumbnails generation

### ISSUE THREAD

**Issue by paiuolo** [pydanny/cookiecutter-django#2418] opened 2020-01-29 10:14 UTC
## Description

Compiling Pillow without libpng-dev installed breaks thumbnail generation for **png** images on *django-filer*.

## Solution

It would be useful to add libpng-dev on Pillow dependencies.

`# Pillow dependencies
&& apk add jpeg-dev zlib-dev freetype-dev lcms2-dev openjpeg-dev tiff-dev tk-dev tcl-dev **libpng-dev** \
`

**Comment by browniebroke** [comment] 2020-01-29 10:33
Thanks for the report. We recently [switched from Alpine to Debian slim](https://github.com/pydanny/cookiecutter-django/pull/2391) as base image, and it looks the project you run was generated prior to this as it uses `apk add`.

I don't know if it's still an issue with our current setup, we would need to confirm this. Can you provide the steps to reproduce the problem? Is it happening on local developement, production or both? Do we have to install `django-filer` or can it be reproduced on a vanilla project?

**Comment by paiuolo** [comment] 2020-01-29 16:19
Thanks for the quick response, I noticed the "Debian Slim" switch right after posting the issue :).
Well done guys!

**Comment by Andrew-Chen-Wang** [comment] 2020-04-16 01:01
Debian slim-buster supports libpng-dev. Shouldn't be a problem anymore. My current image configuration (since I don't see Pillow dependencies...):
```
  # Image dependencies (some for performance)
  && apt-get install -y libtbb2 libtbb-dev libdc1394-22 libjpeg62-turbo libtiff-dev libpng-dev libavformat-dev \
```
Some of these dependencies are also for opencv, e.g. libtbb2 and libjpeg62-turbo. When dealing with Pillow dependencies, check their installation docs.

**Comment by browniebroke** [comment] 2020-09-03 07:50
Since we switched to Debian Slim, Pillow is installed from precompiled wheel. We no longer install from source and compile at install time, so these dependencies shouldn't be needed.

More details on Alpine downsides [here](https://pythonspeed.com/articles/alpine-docker-python/).

I think we can close this issue now.

**Closed by browniebroke** 2020-09-03 07:50 UTC
Labels: bug
