### ISSUE TITLE
Unknown field(s) (first_name, last_name) specified for User in admin

### ISSUE THREAD

**Issue by leopolicastro** [pydanny/cookiecutter-django#3016] opened 2021-01-25 12:52 UTC
## What happened?
I created a new cookiecutter-django project and went through the steps [here](https://cookiecutter-django.readthedocs.io/en/latest/developing-locally.html) to get started.  Then I created a superuser and logged in, but when I click on the edit user link from the admin view I get the following error:

```
django.core.exceptions.FieldError: Unknown field(s) (first_name, last_name) specified for User. Check fields/fieldsets/exclude attributes of class UserAdmin.
```

<img width="1739" alt="image" src="https://user-images.githubusercontent.com/43428385/105708026-d474a980-5ee1-11eb-8da7-63b5c316ecf5.png">

## What should've happened instead?

Instead I should have gotten to the edit user admin page.

## Additional details

* Host system configuration: 
    * Version of cookiecutter CLI (get it with `cookiecutter --version`): `Cookiecutter 1.7.2 from /Users/leo/.virtualenvs/cryptoswap/lib/python3.9/site-packages (Python 3.9)`
    * OS: OSX
    * Python version: Python 3.9.1
    * Docker versions (if using Docker): not using docker
    * ...
* Options selected and/or [replay file](https://cookiecutter.readthedocs.io/en/latest/advanced/replay.html):
    ```json
		{
  "cookiecutter": {
    "project_name": "CryptoSwap",
    "project_slug": "cryptoswap",
    "description": "Bitcoin ATMs",
    "author_name": "Leo Policastro",
    "domain_name": "access.cryptoswap.com",
    "email": "leo-policastro@example.com",
    "version": "0.1.0",
    "open_source_license": "MIT",
    "timezone": "UTC",
    "windows": "n",
    "use_pycharm": "n",
    "use_docker": "n",
    "postgresql_version": "12.3",
    "js_task_runner": "Gulp",
    "cloud_provider": "AWS",
    "mail_service": "Mailgun",
    "use_async": "n",
    "use_drf": "y",
    "custom_bootstrap_compilation": "n",
    "use_compressor": "n",
    "use_celery": "n",
    "use_mailhog": "n",
    "use_sentry": "n",
    "use_whitenoise": "n",
    "use_heroku": "y",
    "ci_tool": "Github",
    "keep_local_envs_in_vcs": "n",
    "debug": "n",
    "_template": "gh:pydanny/cookiecutter-django"
  }
}
    ```
Am I doing something wrong?  I used cookiecutter for a different project last week and I did not have the same issue.

**Comment by browniebroke** [comment] 2021-01-25 12:59
Probably caused by #2998

CC @Andrew-Chen-Wang

**Comment by leopolicastro** [comment] 2021-01-25 13:02
Update: in the users.models file I edited

```python
first_name = None  # type: ignore
last_name = None  # type: ignore
```
to

```python
first_name = models.CharField(max_length=30, null=True, blank=True)
last_name = models.CharField(max_length=30, null=True, blank=True)
```
and everything is working now.

**Comment by browniebroke** [comment] 2021-01-25 13:24
These fields are not actually used in the project, so we should not create them in the DB. We probably missed a change in #2998 which means they are still referenced by a form somewhere.

**Comment by Andrew-Chen-Wang** [comment] 2021-01-25 14:38
oh shoot sorry. I would check UserChangeForm and the users/Admin.py
fieldsets. Will file PR soon.

**Comment by Andrew-Chen-Wang** [comment] 2021-01-25 14:45
Sorry this is just a problem in admin.py and nothing with the forms. You shouldn't use the first_name and last_name field. What you need to do is copy the field sets from `user_admin.UserAdmin.fieldsets` and paste it to only use `name`. Same with some other places list `list_display`, `search_fields`, and `add_fieldsets`. Those three I only listed because I forgot if they include the attributes `first_name` and `last_name`. Just replace those two attributes everywhere with `name`

**Comment by Andrew-Chen-Wang** [comment] 2021-01-25 16:28
@leopolicastro @browniebroke Do either of you want to check #3018 if it's working properly? I just copied from Django's GitHub repo, so I did not test it. Thanks and sorry for the misconfiguration!

**Comment by leopolicastro** [comment] 2021-01-25 16:35
@Andrew-Chen-Wang I can test it tonight if you still need me to.

**Comment by Andrew-Chen-Wang** [comment] 2021-01-25 16:48
Any time's OK. If anyone else gets the error, they can simply head to this issue until the PR is merged.

**Comment by browniebroke** [comment] 2021-01-25 19:41
> I just copied from Django's GitHub repo, so I did not test it

Ah I just saw that (after leaving a comment in the PR). I can probably pick it up later this evening to fix the last bits.

**Comment by browniebroke** [comment] 2021-01-26 12:20
I've updated the PR with a few tests, seems to be working. Could one of you have a quick look? Feedback would be appreciated.

**Closed** 2021-01-26 18:51 UTC
Labels: bug

**Comment by Eraldo** [comment] 2021-07-15 23:26
I am getting this error: `null value in column "first_name" violates not-null constraint`.
After upgrading to Django 3.2.4.
I do not have `first_name` anywhere in the project other than here:
```
class User(NodeUrlMixin, AbstractUser):
    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = CharField(verbose_name=_("name"), blank=True, max_length=255)
    first_name = None  # type: ignore  # <= The only reference to it.
    last_name = None  # type: ignore
```

The error happens when calling `form.save()` on `UserCreationForm`:
```
class UserCreationForm(auth_forms.UserCreationForm):
    class Meta(auth_forms.UserCreationForm.Meta):
        model = User
        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }
```

**Comment by Andrew-Chen-Wang** [comment] 2021-07-15 23:33
@Eraldo Didn't reproduce, but I went through the core Django code and didn't find any mention of `first_name`. Did you just generate this project? If not, then check your migrations. If your migrations still includes first_name or last_name, that's the problem. If not, then try inspecting your db to see if a column of first_name exists. Otherwise, not sure what to say.

**Comment by Eraldo** [comment] 2021-07-16 01:06
Thanks @Andrew-Chen-Wang for the prompt reply.

The project is already a few years old.
I also did a bit of testing now and here is what I could find out...

There is no mention of `first_name` anywhere in my migrations.
If I create a new database from scratch and apply the migrations, I also end up having a `first_name` and `last_name` column.
However the difference is that `not null` is false on a new database while the one I used until now has `not null` set to true.

If I create a new user with the new database, the `first_name` column gets the `<null>` value.
Every user created so far in my older existing database was created with `first_name` set to the empty string.

Is it possible that something with the `UserCreationForm` (or its handling) changed so that it now tries to insert `null` where it previously always used ''?

(PS: Using Postrgres)

**Comment by Andrew-Chen-Wang** [comment] 2021-07-16 01:33
Interesting. Super weird how first_name is not in migrations yet it's created in the db?!

> If I create a new user with the new database, the first_name column gets the <null> value.
Every user created so far in my older existing database was created with first_name set to the empty string.

> Is it possible that something with the UserCreationForm (or its handling) changed so that it now tries to insert null where it previously always used ''?

Did you check if the name column exists in that db? It's possible you're using the wrong model by perhaps not properly specifying the user model in settings or migrations as swappable dependencies? Or maybe a package screwed it up? No clue

**Comment by Eraldo** [comment] 2021-07-16 01:44
Yes, I did check in the database and the columns did get created after dropping the database and running migrate.

I can confirm that I am using the correct model as all the other custom fields are there as well.
Soooo... do I understand it correctly that it does not create these columns at all when you try to reproduce it?

**Comment by Eraldo** [comment] 2021-07-16 01:48
> It's possible you're using the wrong model by perhaps not properly specifying the user model in settings or migrations as swappable dependencies?

In `base.py`:
```
# https://docs.djangoproject.com/en/dev/ref/settings/#auth-user-model
AUTH_USER_MODEL = "users.User"
```

I would not know where else to search. Neither am I aware of a package that would patch it on a new database. *shrug*
I can give you access to the repository if you want to take a look. ^^

**Comment by Andrew-Chen-Wang** [comment] 2021-07-16 01:56
This is what I get in psql, fresh cookiecutter installation:

```
SELECT 
   table_name, 
   column_name, 
   data_type 
FROM 
   information_schema.columns
WHERE 
   table_name = 'users_user';
```

> PS: Nice work with fcm django integration. ;)

Thanks :D

**Comment by Eraldo** [comment] 2021-07-16 02:54
There was indeed some patching magic going on.
You hinted me in the right direction.
I simply removed that code and now recreating does not create these columns anymore.
I can thus safely drop the columns from the existing database.
Thank you @Andrew-Chen-Wang 🙏
