### ISSUE TITLE
Postgres authentication error - cannot run local and production on same machine with Docker

### ISSUE THREAD

**Issue by chase4646** [pydanny/cookiecutter-django#1785] opened 2018-09-05 00:35 UTC
## What happened?

Postgres authentication error makes it impossible to run local and production on same machine (with Docker)

## What should've happened instead?

Unless I have misunderstood, this should be possible, per commit message https://github.com/pydanny/cookiecutter-django/commit/ae9dc2e782ccd734ef0dbe136960b09a8da1a760

> building production stack on the same machine with local doesn't lead to conflicts anymore;

## Steps to reproduce

```
docker-compose -f local.yml build
docker-compose -f local.yml up
```
(hit Ctrl+C)

```
docker-compose -f production.yml build 
docker-compose -f production.yml up
```

Oh dear.

```
postgres_1  | 2018-09-05 00:25:29.091 UTC [32] FATAL:  password authentication failed for user "TjEvhJFUDaxcudETRTQzGgiJqryGIEOM"
postgres_1  | 2018-09-05 00:25:29.091 UTC [32] DETAIL:  Password does not match for user "TjEvhJFUDaxcudETRTQzGgiJqryGIEOM".
postgres_1  |   Connection matched pg_hba.conf line 95: "host all all all md5"
django_1    | Waiting for PostgreSQL to become available...
```

## Host system configuration: OS, Docker & friends' versions etc.

* Ubuntu 18.04
* Docker version 18.06.1-ce, build e68fc7a
* Docker Compose version 1.22.0, build f46880fe

## Project generation options

```
project_name [My Awesome Project]:
project_slug [my_awesome_project]:
description [Behold My Awesome Project!]:
author_name [Daniel Roy Greenfeld]:
domain_name [example.com]:
email [daniel-roy-greenfeld@example.com]:
version [0.1.0]:
Select open_source_license:
1 - MIT
2 - BSD
3 - GPLv3
4 - Apache Software License 2.0
5 - Not open source
Choose from 1, 2, 3, 4, 5 [1]:
timezone [UTC]:
windows [n]:
use_pycharm [n]:
use_docker [n]: y
Select postgresql_version:
1 - 10.4
2 - 10.3
3 - 10.2
4 - 10.1
5 - 9.6
6 - 9.5
7 - 9.4
8 - 9.3
Choose from 1, 2, 3, 4, 5, 6, 7, 8 [1]:
Select js_task_runner:
1 - None
2 - Gulp
Choose from 1, 2 [1]:
custom_bootstrap_compilation [n]:
use_compressor [n]:
use_celery [n]:
use_mailhog [n]:
use_sentry [n]: y
use_whitenoise [n]: y
use_heroku [n]:
use_travisci [n]:
keep_local_envs_in_vcs [y]:
debug [n]:
```

**Comment by sfdye** [comment] 2018-09-06 02:33
This may be a bug, but why would you want to build both `local` and `production` on the same machine?

**Comment by taxate-mtd** [comment] 2018-09-06 08:33
@browniebroke Appreciate you getting back to me. I'll try this today and report back.

@sfdye Current project requires 4 separate environments: dev, test, production and demo. We're early enough stage that it doesn't make sense to use a separate server for each.

**Comment by chase4646** [comment] 2018-09-06 08:34
browniebroke Appreciate you getting back to me. I'll try this today and report back.

@sfdye Current project requires 4 separate environments: dev, test, production and demo. We're early enough stage that it doesn't make sense to use a separate server for each.

**Comment by webyneter** [comment] 2018-11-01 10:35
@chase4646 mind trying it out again, with our latest master?

**Comment by chase4646** [comment] 2018-11-01 13:36
Will struggle as now full time on another project...

Anyone else with this issue able to confirm?

**Comment by uunbound** [comment] 2018-11-02 14:15
I have the same issue with postgresql service not being started on `up` command. Did initialize my project today with latest master.

**Comment by steverecio** [comment] 2018-11-15 01:58
I have this issue from time to time after rebuilding. Only using local configs. I usually have to run both `docker system prune` and `docker volume prune`.

**Comment by browniebroke** [comment] 2019-03-15 14:42
Closing as duplicate of #1678

**Closed by browniebroke** 2019-03-15 14:42 UTC
Labels: docker
