### ISSUE TITLE
Unable to run first migrations/runserver: "config/settings/.env doesn't exist"

### ISSUE THREAD

**Issue by alexbumpers** [pydanny/cookiecutter-django#1000] opened 2017-01-19 04:07 UTC
I am following the guide here: http://cookiecutter-django.readthedocs.io/en/latest/developing-locally.html#setting-up-env-vars-for-production. I have also been going through the ReadMe. I created my virtualenv, followed the instructions on the guide to a T, but whenever I run python manage.py migrate or python manage.py runserver, I get the error below. Can someone help me figure out why I'm running into this issue? I should note that I accepted the defaults for all of the options when starting this, as that's what the tutorial said to do. 

/Users/user/cc_test/user/cc_test/lib/python3.6/site-packages/environ/environ.py:608: UserWarning: /Users/user/cc_test/my_favorite_cookie/config/settings/.env doesn't exist - if you're not configuring your environment separately, create one.
  "environment separately, create one." % env_file)
Traceback (most recent call last):
  File "manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/user/cc_test/user/cc_test/lib/python3.6/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/user/cc_test/user/cc_test/lib/python3.6/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/Users/user/cc_test/user/cc_test/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/user/cc_test/user/cc_test/lib/python3.6/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Users/user/cc_test/user/cc_test/lib/python3.6/site-packages/django/apps/config.py", line 116, in create
    mod = import_module(mod_path)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 676, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Users/user/cc_test/user/cc_test/lib/python3.6/site-packages/debug_toolbar/apps.py", line 12, in <module>
    from debug_toolbar.middleware import DebugToolbarMiddleware
  File "/Users/user/cc_test/user/cc_test/lib/python3.6/site-packages/debug_toolbar/middleware.py", line 17, in <module>
    from debug_toolbar.toolbar import DebugToolbar
  File "/Users/user/cc_test/user/cc_test/lib/python3.6/site-packages/debug_toolbar/toolbar.py", line 151, in <module>
    urlpatterns = DebugToolbar.get_urls()
  File "/Users/user/cc_test/user/cc_test/lib/python3.6/site-packages/debug_toolbar/toolbar.py", line 145, in get_urls
    for panel_class in cls.get_panel_classes():
  File "/Users/user/cc_test/user/cc_test/lib/python3.6/site-packages/debug_toolbar/toolbar.py", line 118, in get_panel_classes
    mod = import_module(panel_module)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/user/cc_test/user/cc_test/lib/python3.6/site-packages/debug_toolbar/panels/sql/__init__.py", line 1, in <module>
    from debug_toolbar.panels.sql.panel import SQLPanel  # noqa
  File "/Users/user/cc_test/user/cc_test/lib/python3.6/site-packages/debug_toolbar/panels/sql/panel.py", line 12, in <module>
    from debug_toolbar.panels.sql import views
  File "/Users/user/cc_test/user/cc_test/lib/python3.6/site-packages/debug_toolbar/panels/sql/views.py", line 7, in <module>
    from debug_toolbar.panels.sql.forms import SQLSelectForm
  File "/Users/user/cc_test/user/cc_test/lib/python3.6/site-packages/debug_toolbar/panels/sql/forms.py", line 13, in <module>
    from debug_toolbar.panels.sql.utils import reformat_sql
  File "/Users/user/cc_test/user/cc_test/lib/python3.6/site-packages/debug_toolbar/panels/sql/utils.py", line 5, in <module>
    import sqlparse
  File "/Users/user/cc_test/user/cc_test/lib/python3.6/site-packages/sqlparse/__init__.py", line 15, in <module>
    from sqlparse import filters
  File "/Users/user/cc_test/user/cc_test/lib/python3.6/site-packages/sqlparse/filters/__init__.py", line 16, in <module>
    from sqlparse.filters.tokens import KeywordCaseFilter
  File "/Users/user/cc_test/user/cc_test/lib/python3.6/site-packages/sqlparse/filters/tokens.py", line 26, in <module>
    class KeywordCaseFilter(_CaseFilter):
TypeError: '_TokenType' object is not callable

**Comment by griff-rees-RIT** [comment] 2017-01-19 05:26
The error `/Users/user/cc_test/my_favorite_cookie/config/settings/.env doesn't exist - if you're not configuring your environment separately, create one.` is probably the issue.

Try copying `env.example` to `.env`, and edit as suits your configuration for running locally (passwords and SQL configuration should go in `.env`)

**Comment by kerstin** [comment] 2017-01-19 12:27
See also #490 and #951.

**Comment by alexbumpers** [comment] 2017-01-19 17:25
I did as instructed and am still experiencing the same issue. I followed @Eraldo's answer on #490 but got caught up on step 2. I have developed on Django (by itself) before, but not on any of these templates, and I'm not sure what to put on the values in the .env file if I'm just trying to create something relatively basic to use on my local machine.

**Comment by kerstin** [comment] 2017-01-19 22:44
@alexbumpers Tbh, I didn't check your error messages but went by the comment you received.

If you use the newest version of cookiecutter, I believe the `.env` file should get read automatically if you place it in the right directory... the one where all the other settings go (either `settings` or `config` – sorry, I'm currently not on a machine with a cookiecutter or, in fact, any Django project on it).

Now if you wanted to e.g. put info about your database in your .env file, you'd do it like @TidyData did in the PR they submitted in #951. One of the settings files, possibly `common.py` (iirc), already tries to read the `DATABASE_URL` variable (but defaults to something else if it's not provided).

**Comment by alexbumpers** [comment] 2017-01-20 00:58
Still having no luck, unfortunately. I'm just looking to get an extremely basic Django Cookiecutter app started locally to toy around with, no need for anything crazy, no need for Docker or Heroku, etc. At this point I'd just like someone to point me in the direction of a basic walkthrough or something.

**Comment by pydanny** [comment] 2017-01-20 02:22
@mjhea0 and the @realpython team maintains a walkthrough of Cookiecutter Django:  https://realpython.com/blog/python/development-and-deployment-of-cookiecutter-django-via-docker/

FWIW, I don't use the `.env` method myself. I define local environment variables in my `.bash_profile` and use it that way.

**Comment by kerstin** [comment] 2017-01-20 07:40
But that walkthrough uses Docker. For people unfamiliar with Docker who don't want to or can't use it (right now), that's not so helpful. /:

@alexbumpers Have your errors changed? Could the problem be that you're using Python 3.6? Cookiecutter doesn't seem to officially support 3.6 (yet), see the README file. I know that I ran into problems trying to use it with 3.6 (I was aware of the missing support but thought I'd give it a try), so I'd suggest you try again with Python 3.5.

**Comment by jayfk** [comment] 2017-01-20 08:25
Why do we even load `.env` in vanilla Python? This was meant to be run with docker in *production* mode, there is no need to load it for vanilla Python projects during *development*.

**Comment by kerstin** [comment] 2017-01-20 09:15
There is no *need* if you put your variables elsewhere anyway but it makes sense even for "vanilla" Python for people who are used to using `.env` files? I've been using them for longer than I've been using Django, so just sticking to them is easier/faster for me than even trying to figure out other ways?

Your comment sounds kind of dismissive of how other people use stuff ("I don't use x, so we (this project, anyone using this project) don't need to use x").

**Comment by jayfk** [comment] 2017-01-20 09:47
> Your comment sounds kind of dismissive of how other people use stuff ("I don't use x, so we (this project, anyone using this project) don't need to use x").

That wasn't my intention. You are free to use `.env` files wherever you go and I agree that it makes sense to use them with vanilla Python.

The thing is, Cookiecutter Django supports so many runtime configurations that you have to draw a line somewhere on what is supported under what configuration out of the box. The `.env` file was designed to be used with docker in production mode (because you have no other way to tell docker about your environment without checking in the your environment variables other than using an `.env` file).

Some of these variables don't even make sense using with vanilla Python. `POSTGRES_USER` and `POSTGRES_PASSWORD` are picked up in `entrypoint.sh` to construct the postgres URL.

Somewhere along the line of supporting as many configurations as possible we've introduced a bug where the `.env` file is read by default which shouldn't be the case. The local environment has all variables set in `local.py` and that's it.

Again, If you are used to `.env` files there's nothing wrong with using them during local development.

**Comment by kerstin** [comment] 2017-01-20 10:26
> The thing is, Cookiecutter Django supports so many runtime configurations that you have to draw a line somewhere on what is supported under what configuration out of the box.

Of course. I think for new users the .env file is just mostly confusing because its usage is not documented but it's included in installs where the user picked "No" for Docker. (Same for the PyCharm Docker run configurations, of which I got 8.)

**Comment by kerstin** [comment] 2017-01-20 10:37
And I don't mind it being included! I (personally) just would have appreciated some info about it, and I've meanwhile learned others feel the same way.

I also asked 
> What... exactly is the plan for documenting this? 

in the other issue but so far, no-one's reacted to it. With one other question of mine regarding docs open and unanswered, and other issues/PRs regarding the `.env` file open & unanswered, I don't want to invest time in a PR which might not get used in the end.

**Comment by alexbumpers** [comment] 2017-01-20 15:01
@kerstin Unfortunately I have not resolved the issue still... I am using Python 3.6 though, so I'll test a different version of Python later today if I get the chance.

At this point, I just want to get something off the ground and be able to play around with it a bit on my local computer, but I am having quite a bit of trouble getting around this .env issue. I am admittedly not very experienced with using environment variables, so my lack of knowledge in that realm is certainly not helping!

**Comment by luzfcb** [comment] 2017-01-20 15:15
@alexbumpers Maybe, this is not a cookiecutter-django problem and .env file, but a bug in `sqlparse`

They made some changes in the master branch regarding compatibility with python3.6.
try installing sqlparse from the available code in the master branch and check If it works correctly:

load your virtualenv and run:

```bash
pip install -e git+https://github.com/andialbrecht/sqlparse#egg=sqlparse
```

**Comment by alexbumpers** [comment] 2017-01-20 15:32
@luzfcb I will try this later and update after I've done so, thanks! I ran a pip install sqlparse last night to see if that would resolve it, but it didn't seem to do anything (I may have been missing the issue entirely by doing that). I'll try your pip install later and return with the results.

**Comment by kerstin** [comment] 2017-01-20 23:02
Maybe try with Python 3.5 first to make sure it's not the Python version. (In case you run into more issues later with 3.6.)

**Comment by Afrowave** [comment] 2017-02-09 19:01
I was informed by some Laravel folk that a .env is used in their setup as a place for local host settings fro development. That way, no settings file is touched at all for dev, staging or production.

So I thought that the Docker `.env` can exist in the root as it is and the ``config/.env`` version can be configured for local and staging if necessary.

**Comment by alexbumpers** [comment] 2017-02-09 19:48
Sorry for responding to this so late. I ended up just running this in a Docker container. While I still encounter the issue, I'm able to develop locally in the container and do what I need to do with seemingly no issues.

Python 3.5/3.6 didn't seem to matter once running in a Docker container.

**Comment by pydanny** [comment] 2017-04-20 22:24
I'm going to close this. If this issue continues to be a problem, please reopen this issue.

**Closed by pydanny** 2017-04-20 22:24 UTC

**Comment by NathanQ** [comment] 2017-06-01 20:50
The .env file is an issue for me. My .env info is ignored by the settings. Well, maybe not ignored. If it's there, the warning is suppressed, but the settings aren't being used. I don't know how it work.

Maybe because it's been a hangup for me or maybe because I really don't understand how it works, but I fail to see the benefit of using a text file over importing a gitignored python settings file.

**Comment by luzfcb** [comment] 2017-06-01 21:52
@NathanQ 
by default, a cookiecutter-django based project, expects that you to manually set all the environment variables that will be used by the project. All available environment variables are listed at https://cookiecutter-django.readthedocs.io/en/latest/settings.html#settings

The reason for the `.env` file being explicitly ignored in `.gitignore`, is because some of the environment variables contain data that should never be public and should never be versioned in git, such as passwords. ( for example, Sendgrid temporarily locks your account if you include your Sendgrid API access key in a public repository in github)

In a development environment (your own machine), manually set the environment variables, in each terminal you use can be a bit tedious, to get around this, you can manually run 
`export DJANGO_READ_DOT_ENV_FILE=True` (Remember, this must be done manually.).

This option causes [django-environ](https://github.com/joke2k/django-environ) to read the .env file and look for the environment variables in it. ( django-environ does not do this by default.


This feature was introduced in https://github.com/pydanny/cookiecutter-django/pull/985

this explanation helped or complicated?

**Comment by NathanQ** [comment] 2017-06-02 19:46
@luzfcb 
Thanks you for your help. After seeing how it works, I now like django-environ's functionality of providing a default value or the env value in the settings. To your point about .env noted in the .gitignore, can't any? First deployment was not fun and adding this little complexity on **deployment** day was, well, one more thing. 

Thanks again!

**Comment by aduuna** [comment] 2018-07-30 06:19
The error is sql parse error, has got nothing to do with docker or whatsoever people are suggesting. 

There is a minor issue with sql parser on python 3.6.0. Upgrading your python version should fix the problem. 

You can grab the 3.6.6 version which will install on top of 3.6.0 (in the same directory as 3.6.0). Concerning the virtual environment, just create a new one, copy and paste the site-packages from the old one into Envs/<new_env>/Lib/ and it's upgraded 😉
