### ISSUE TITLE
django.core.exceptions.ImproperlyConfigured: Set the DATABASE_URL environment variable

### ISSUE THREAD

**Issue by EVENFATE** [pydanny/cookiecutter-django#2821] opened 2020-09-13 04:19 UTC
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/environ/environ.py", line 273, in get_value
    value = self.ENVIRON[var]
  File "/usr/local/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'DATABASE_URL'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 60, in execute
    super().execute(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 67, in handle
    if not settings.DEBUG and not settings.ALLOWED_HOSTS:
  File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 76, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 63, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 142, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/config/settings/local.py", line 1, in <module>
    from .base import *  # noqa
  File "/app/config/settings/base.py", line 44, in <module>
    DATABASES = {"default": env.db("DATABASE_URL")}
  File "/usr/local/lib/python3.8/site-packages/environ/environ.py", line 204, in db_url
    return self.db_url_config(self.get_value(var, default=default), engine=engine)
  File "/usr/local/lib/python3.8/site-packages/environ/environ.py", line 277, in get_value
    raise ImproperlyConfigured(error_msg)
django.core.exceptions.ImproperlyConfigured: Set the DATABASE_URL environment variable
```

the errors happend when pycharm runserver,  how to solve this?

**Comment by NicoDevops** [comment] 2020-09-18 15:22
Hi, 
Did you export your DATABASE_URL from your terminal before running your command?

**Comment by Andrew-Chen-Wang** [comment] 2020-09-23 20:16
@EVENFATE This may be due to the docs service. Check #2674

**Comment by NicoDevops** [comment] 2020-09-24 19:37
@Andrew-Chen-Wang 

Hi, for me he does not seems to run docker, or we can't know yet from the actual logs,
as it is mentioned, the error is from the fact that environ package (at the beginning of. base.py  ) raise a key value error.

`File "/usr/local/lib/python3.8/site-packages/environ/environ.py", line 273, in get_value
value = self.ENVIRON[var]
File "/usr/local/lib/python3.8/os.py", line 675, in getitem
raise KeyError(key) from None
KeyError: 'DATABASE_URL'`

which also can be see at the end of the logs: 

File "/app/config/settings/base.py", line 44, in 
`DATABASES = {"default": env.db("DATABASE_URL")}  # <==. key: value that are actually missing.`

If an error regarding DOCKER should happen. It would be later, so "use export" can be a way around to run the full package, either from docker-compose or from within a python virtualenv.

Perhaps, if I remember well, base.py is calling from local.py in dev environment.
So, the first error likely to occur is DATABASE_URL, then CELERY_BROKER_URL (eventually if it was requested to be configure like so while initiating the project. and finally if there is an issue with docker you will be notified for nor running your app in Docker environment.

**Comment by Andrew-Chen-Wang** [comment] 2020-09-25 01:16
I was inferencing that OP was using Docker based on the traceback from this: `File "/app/config/settings/local.py", line 1, in ` since we set the Dockerfile dir to be `/app`.

The bug fix that I filed is basically what you described: DATABASE_URL couldn't find the environment variable, and then you couldn't find CELERY_BROKER_URL. If you try to create a new cookiecutter-django project using Docker, you'll see that's exactly what errors from the docs service.

**Comment by NicoDevops** [comment] 2020-09-25 12:45
Yep you are right, i agree

**Comment by browniebroke** [comment] 2020-11-16 18:23
Going to close this as the docs service has been fixed in #2920 

Feel free to reopen or create a new issue if the problem persists in a freshly generated project.

**Closed by browniebroke** 2020-11-16 18:23 UTC
Labels: question

**Comment by enry2307-enry** [comment] 2021-11-14 10:59
@Yugalakisora did you find any solution?

**Comment by Yugalakisora** [comment] 2021-11-14 11:02
No, but I think that most likely it will be caused by restrictions to connect to the URL, because it is an external server and maybe it is not working

**Comment by TElphee01** [comment] 2021-11-21 23:06
Holy cow - whole weekend gone on this one.... Here we go -
It turns out in your .local/.postgres file, the DATABASE_URL is not set. So add this line
DATABASE_URL=postgres://<Your Username>:<Your postgres DB password>@postgres:5432/<Your postgres db name>
Some folks suggest DATABASE_URL=postgres://<Your Username>:<Your postgres DB password>@postgres:127.0.0.1/<Your postgres db name> but this did not work for me....

Once that was set, I was not able to run the standard (python manage.py createsuperuser) command. Since I'm running docker I needed (docker exec -it <your Django Container ID> python manage.py createsuperuser). You can find the container ID by running  command (docker ps). Hope this helps. Shout out to Akash Vibhute here 
https://gitter.im/pydanny/cookiecutter-django?at=5eb16ed6d898fe7a3768977f

**Comment by Andrew-Chen-Wang** [comment] 2021-11-22 01:09
@TElphee01 Correct, it is set in entrypoint under the compose/django directory. If you want to run a command like shell, you'll need to do `docker-compose -f local.yml run --rm django python manage.py shell`

**Comment by TElphee01** [comment] 2021-11-24 14:09
@Andrew-Chen-Wang  Yes sir that did work as well! Thank you for your help!

**Comment by subbydavid** [comment] 2022-04-19 12:43
@Andrew-Chen-Wang Im getting this for one of my containers deployed on AKS. It works fine on vm but not when i deployed to AKS. I set env variable in configmap.
What would you advise i do next please

**Comment by Andrew-Chen-Wang** [comment] 2022-04-19 12:46
I don't know what AKS is but I assume the reason you're bumping into this error is because you're trying to run something via the docker file rather than the compose file

**Comment by subbydavid** [comment] 2022-04-19 13:03
Apologies AKS is azure kubernetes service. Can i not run the dockerfile instead of docker compose file?

**Comment by Andrew-Chen-Wang** [comment] 2022-04-19 13:43
the compose file includes an entry point which the dockerfile does not include. What you could do is add entrypoint stuff to your start file. The entrypoint file just ensures all necessary services like Postgres is running

**Comment by habenhkt** [comment] 2022-05-10 06:21
hey gusy, am facing this error please help


web_1    | Traceback (most recent call last):
web_1    |   File "/usr/lib/python3.8/site-packages/environ/environ.py", line 273, in get_value
web_1    |     value = self.ENVIRON[var]
web_1    |   File "/usr/lib/python3.8/os.py", line 675, in __getitem__
web_1    |     raise KeyError(key) from None
web_1    | KeyError: 'STRIPE_TEST_PUBLIC_KEY'
web_1    | 
web_1    | During handling of the above exception, another exception occurred:
web_1    | 
web_1    | Traceback (most recent call last):
web_1    |   File "/usr/bin/waitress-serve", line 8, in <module>
web_1    |     sys.exit(run())
web_1    |   File "/usr/lib/python3.8/site-packages/waitress/runner.py", line 270, in run
web_1    |     app = resolve(module, obj_name)
web_1    |   File "/usr/lib/python3.8/site-packages/waitress/runner.py", line 211, in resolve
web_1    |     obj = __import__(module_name, fromlist=segments[:1])
web_1    |   File "/opt/webapp/sway_backend_15594/wsgi.py", line 16, in <module>
web_1    |     application = get_wsgi_application()
web_1    |   File "/usr/lib/python3.8/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
web_1    |     django.setup(set_prefix=False)
web_1    |   File "/usr/lib/python3.8/site-packages/django/__init__.py", line 19, in setup
web_1    |     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
web_1    |   File "/usr/lib/python3.8/site-packages/django/conf/__init__.py", line 79, in __getattr__
web_1    |     self._setup(name)
web_1    |   File "/usr/lib/python3.8/site-packages/django/conf/__init__.py", line 66, in _setup
web_1    |     self._wrapped = Settings(settings_module)
web_1    |   File "/usr/lib/python3.8/site-packages/django/conf/__init__.py", line 157, in __init__
web_1    |     mod = importlib.import_module(self.SETTINGS_MODULE)
web_1    |   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
web_1    |     return _bootstrap._gcd_import(name[level:], package, level)
web_1    |   File "/opt/webapp/sway_backend_15594/settings.py", line 293, in <module>
web_1    |     STRIPE_TEST_PUBLIC_KEY = env('STRIPE_TEST_PUBLIC_KEY', 'pk_test_51GtDNLH3O0A61qqEhYxXEKeOf9R7nGgn6BerrgCqoQWNp1m5iyoeMGpn32uSYcV7lcrwdAoW2n3kNNn56QVt2PYm00ZwiVL119')
web_1    |   File "/usr/lib/python3.8/site-packages/environ/environ.py", line 123, in __call__
web_1    |     return self.get_value(var, cast=cast, default=default, parse_default=parse_default)
web_1    |   File "/usr/lib/python3.8/site-packages/environ/environ.py", line 277, in get_value
web_1    |     raise ImproperlyConfigured(error_msg)
web_1    | django.core.exceptions.ImproperlyConfigured: Set the STRIPE_TEST_PUBLIC_KEY environment variable
backend_web_1 exited with code 1

**Comment by foarsitter** [comment] 2022-05-10 06:26
You are setting `STRIPE_TEST_PUBLIC_KEY` without the `default` keyword for `env`.

**Comment by habenhkt** [comment] 2022-05-10 06:27
here is my env

DEBUG=1
HOST=localhost
PORT=8000
DATABASE_URL=postgres://postgres:<postgres_pwd>@postgres:5432/postgres
REDIS_URL=redis://redis:6379
SECRET_KEY=<random_string_goes_here>

**Comment by foarsitter** [comment] 2022-05-10 06:32
@habenhkt are you aware that you are asking a question in a closed Issue? Besides that, the issue section of github is for issues concerning the project. Your problem is more suitable for in QA site like stackoverflow or the discussion section. 

Regarding your question, check the `env()` method, it is missing the keyword `default` (settings.py, line 293).

**Comment by morenoh149** [comment] 2022-12-22 15:47
> @TElphee01 Correct, it is set in entrypoint under the compose/django directory. If you want to run a command like shell, you'll need to do `docker-compose -f local.yml run --rm django python manage.py shell`

this works for me. It feels unintuitive, I think many ppl expect to be able to open a shell on the webserver container and run django management commands.
