### ISSUE TITLE
UserDetailView fails on mixed-case usernames

### ISSUE THREAD

**Issue by jandrewstre** [pydanny/cookiecutter-django#1020] opened 2017-02-05 04:47 UTC
UserDetailView fails to find the user based on slug if the username is not stored in lowercase, which is likely to be the case given that django-allauth preserves case when storing usernames by default.

**Comment by pydanny** [comment] 2017-04-21 15:24
I encountered something like this not too long ago. Let's see if we can write a test for it, shall we?

**Comment by browniebroke** [comment] 2020-03-17 18:24
We couldn't reproduce in #2234 so I'm closing this.

**Closed by browniebroke** 2020-03-17 18:24 UTC
Labels: bug, good first issue, help wanted
